### ISSUE TITLE
Avro parser does not store sub definitions

### ISSUE THREAD

**Issue by kolb0401** [asyncapi/avro-schema-parser#111]
#### Describe the bug
When parsing an Avro document the parser does not store the seen record definitions leading to not found errors in valid schemas. 

#### How to Reproduce

To reproduce just embed the following schema in a valid asyncAPI document and run it through the generator. 

```avro
{
  "type": "record",
  "name": "ConnectionRequested",
  "namespace": "com.foo.connections",
  "doc": "An example schema to illustrate the issue",
  "fields": [
    {
      "name": "metadata",
      "type": {
        "type": "record",
        "name": "EventMetadata",
        "namespace": "com.foo",
        "doc": "Metadata to be associated with every published event",
        "fields": [
          {
            "name": "id",
            "type": {
              "type": "string",
              "logicalType": "uuid"
            },
            "doc": "Unique identifier for this specific event"
          },
          {
            "name": "timestamp",
            "type": {
              "type": "long",
              "logicalType": "timestamp-millis"
            },
            "doc": "Instant the event took place (not necessary when it was published)"
          },
          {
            "name": "correlation_id",
            "type": [
              "null",
              {
                "type": "string",
                "logicalType": "uuid"
              }
            ],
            "doc": "id of the event that resulted in this\nevent being published (optional)",
            "default": null
          },
          {
            "name": "publisher_context",
            "type": [
              "null",
              {
                "type": "map",
                "values": {
                  "type": "string",
                  "avro.java.string": "String"
                },
                "avro.java.string": "String"
              }
            ],
            "doc": "optional set of key-value pairs of context to be echoed back\nin any resulting message (like a richer\ncorrelationId.\n\nThese values are likely only meaningful to the publisher\nof the correlated event",
            "default": null
          }
        ]
      }
    },
    {
      "name": "auth_code",
      "type": {
        "type": "record",
        "name": "EncryptedString",
        "namespace": "com.foo",
        "doc": "A string that was encrypted with AES (using CTR mode), its key encrypted with RSA, and the nonce used for the encryption.",
        "fields": [
          {
            "name": "value",
            "type": "bytes",
            "doc": "A sequence of bytes that has been AES encrypted in CTR mode."
          },
          {
            "name": "nonce",
            "type": "bytes",
            "doc": "A nonce, used by the CTR encryption mode for our encrypted value. Not encrypted, not a secret."
          },
          {
            "name": "key",
            "type": "bytes",
            "doc": "An AES key, used to encrypt the value field, that has itself been encrypted using RSA."
          }
        ]
      },
      "doc": "Encrypted auth_code received when user authorizes the app."
    },
    {
      "name": "refresh_token",
      "type": "com.foo.EncryptedString",
      "doc": "Encrypted refresh_token generated by using clientId and clientSecret."
    },
    {
      "name": "triggered_by",
      "type": {
        "type": "string",
        "logicalType": "uuid"
      },
      "doc": "ID of the user who triggered this event."
    }
  ]
}
```

Running the following through the parser will result in: 

```
Something went wrong:
Error: undefined type name: com.foo.EncryptedString
    at parse (/Users/jkolb/.nvm/versions/node/v12.16.2/lib/node_modules/@asyncapi/generator/node_modules/@asyncapi/parser/lib/parser.js:112:11)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

#### Expected behavior
The above schema should parse just fine as `com.foo.EncryptedString` was defined earlier in the schema which is valid Avro.

**Comment by kolb0401** [comment]
The approach I would like to contribute back is to implement an accumulator pattern of any sub-record definitions into the following function: 

https://github.com/asyncapi/avro-schema-parser/blob/9d1f4b93f524554b0d37ac026a3e35ebc37d8e1d/to-json-schema.js#L139
